Calculate relative window size
crossterm-rs/crossterm-input pull request #11
Opened 2019-10-20 14:12 UTC by TimonPost

Fixes: https://github.com/crossterm-rs/crossterm/issues/278

Result: 

TOP, LEFT click:

![image](https://user-images.githubusercontent.com/19969910/67160756-5166ba00-f354-11e9-8017-300778777c86.png)

Previously: 

TOP, LEFT click
![image](https://user-images.githubusercontent.com/19969910/67160770-680d1100-f354-11e9-9f1c-f9cba072fd71.png)

2019-10-20 14:17 UTC, TimonPost commented
@zrzka can you check on macos/linux if the cursor positions from input events are relative to the current window or absolute to the current screen buffer. Otherwise, this patch is not needed to sync the behavior. But I am pretty convinced it was relative to the window... We better double-check. 

This PR should be merged before the release

2019-10-20 16:02 UTC, zrzka requested changes

2019-10-20 16:02 UTC, zrzka commented on src/input/windows.rs
> +        .unwrap()
Do **not** introduce new `unwrap()` calls. I spent quite a lot of time when I was trying to remove lot of them. There're still around, but I'm not gonna accept new ones.

The `parse_mouse_event_record` result type should be changed from `Option<crate::MouseEvent>` to `Result<Option<crate::MouseEvent>>>`.

The `handle_mouse_event` already returns `Result<...>`, so, it's an easy change. `handle_mouse_event` will just map `Ok(Some(MouseEvent))` to `Ok(Some(InputEvent::Mouse(MouseEvent)))`.

2019-10-20 16:03 UTC, zrzka commented
@TimonPost here's my test code ...

```rust
use std::io::Write;

use crossterm_input::{input, InputEvent, KeyEvent, RawScreen, Result};

fn read_asynchronously() -> Result<()> {
    let _raw = RawScreen::into_raw_mode()?;

    let input = input();

    input.enable_mouse_mode()?;

    let mut stdin = input.read_async();

    loop {
        if let Some(key_event) = stdin.next() {
            match key_event {
                InputEvent::Keyboard(KeyEvent::Esc) => break,
                InputEvent::Keyboard(KeyEvent::Up) => {
                    let mut stdout = std::io::stdout();
                    let _ = write!(stdout, "\x1B[5T");
                    let _ = stdout.flush();
                }
                InputEvent::Keyboard(KeyEvent::Down) => {
                    let mut stdout = std::io::stdout();
                    let _ = write!(stdout, "\x1B[5S");
                    let _ = stdout.flush();
                }
                ie => println!("\r{:?}", ie),
            };
        }
    }

    input.disable_mouse_mode()
}

fn main() -> Result<()> {
    read_asynchronously()
}
```

... no matter how many times I hit `Up`/`Down`, the top/left mouse click is reported as `0, 0`.

2019-10-20 16:08 UTC, zrzka commented
Also there's no changelog entry, but for now, **don't add it**. Once you fix the `unwrap()` and the PR will be merged, I'll add it to the deprecated-release branch (to avoid merge conflict) and will also add it to the release-0.12 PR in the crossterm crate.

2019-10-20 19:11 UTC, TimonPost commented on src/input/windows.rs
> +        .unwrap()
right, agree was in a hurry ;)

2019-10-20 19:22 UTC, zrzka commented on src/input/windows.rs
> +        .unwrap()
Still one unwrap - ScreenBuffer.current().unwrap() :)

2019-10-20 20:05 UTC, TimonPost commented
![image](https://user-images.githubusercontent.com/19969910/67164809-afa89280-f37e-11e9-8e1b-b28001796c7f.png)

2019-10-20 20:08 UTC, zrzka approved these changes
Happy :)

2019-10-20 20:15 UTC, zrzka commented
Changelogs updated [here](https://github.com/crossterm-rs/crossterm-input/pull/10/commits/e4c91487b0c3e58f68364f85a9b1de35b2ef429e) & [here](https://github.com/crossterm-rs/crossterm/pull/277/commits/394df85c2f8dcaed9873564014b2827b0c1f15cb).

2019-10-21 08:30 UTC, zrzka commented
@TimonPost made more tests on Linux & macOS. Both behaves in the same way, top/left is 0,0 no matter how many times I scroll up/down. If you tested this on Windows, we can merge it.

2019-10-21 16:52 UTC, merged